# Generated by Django 4.1 on 2022-08-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descriacao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'Avançado'), ('B', 'Básico'), ('I', 'Intermediário')], default='B', max_length=1),
        ),
    ]
