# Generated by Django 4.0.6 on 2022-08-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=100),
        ),
    ]
